pub trait TRAIT_WITH_CONST {
    const CONST_ON_TRAIT: i32;
}

struct STRUCT_WITH_TRAIT_WITH_CONST_WILL_REMOVE_IMPL;

impl TRAIT_WITH_CONST for STRUCT_WITH_TRAIT_WITH_CONST_WILL_REMOVE_IMPL {
    const CONST_ON_TRAIT: i32 = 0;
}


struct STRUCT_WITH_CONST {
    CONST_ON_TRAIT: i32
}
